#!/bin/bash

mkdir -p out/history
OUT=out/history/`git rev-parse --short HEAD`.txt

time `dirname $0`/ttt 10000 50 | tee $OUT

awk <$OUT '{ sum += 8*$1 + 4*$2 + 2*$3 + 1*$4; } END { print "total", sum; }'
