#!/bin/bash

CWD=`dirname $0`

begin=$1
step=$2
lineup=MSSS

out=out/results
rm -rf $out
mkdir -p $out

seed=$begin
for map in DEFAULT CHEESER MAP01 MAP02 MAP03
do
    file=$out/$map-$lineup.out
    end=`expr $seed + $step - 1`
    $CWD/mt $seed $end $map $lineup >$file
    echo "$map $lineup"
    awk 'BEGIN { a[1]=0;a[2]=0;a[3]=0;a[4]=0; } { a[$1]++; if ($1<1||$1>4) print "oh dear"; } END { print a[1],a[2],a[3],a[4]; }' <$file
    seed=`expr $end + 1`
done
