#!/bin/bash

# Usage: ./ttt 10000 100

CWD=`dirname $0`

begin=$1
step=$2
lineup=MSSS

out=out/results
rm -rf $out
mkdir -p $out

seed=$begin
for map in MAP01 MAP05 DEFAULT MAP04 MAP03 FEFER MAP06 MAP02 CHEESER
do
    end=`expr $seed + $step - 1`
    $CWD/t $seed $end $map $lineup $out/$map-$lineup.out
    seed=`expr $end + 1`
done
